# Appwrite environment variables
APPWRITE_ENDPOINT = ''
APPWRITE_PROJECT = 'councillor'
APPWRITE_KEY = ''
APPWRITE_DB_NAME = 'councillor'

ROLE_REQUIREMENT_ID = None
DAYS_REQUIREMENT = 180
VOTING_CHANNEL_ID = None
BOT_TOKEN = ''
DEBUG_MODE = False
