APPWRITE_ENDPOINT = 'https://appwrite.igportals.eu/v1'
APPWRITE_PROJECT = 'councillor'
APPWRITE_KEY = ''
APPWRITE_DB_NAME = 'councillor'

ROLE_REQUIREMENT_ID = None
DAYS_REQUIREMENT = 180
VOTING_CHANNEL_ID = None
DISCORD_TOKEN = ''
GUILD_ID = None
DEBUG_MODE = False

